[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.14.2", default-features = false, features = ["highs"] }
regex = "1.12.2"

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "benchmarks"
harness = false
